apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-3-apifeed
  labels:
    app: udacity-3-apifeed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-3-apifeed
  template:
    metadata:
      labels:
        app: udacity-3-apifeed
    spec:
      containers:
      - name: udacity-3-apifeed
        image: fjenkel/udacity-3-apifeed
        ports:
        - containerPort: 8080