apiVersion: v1
kind: Service
metadata:
  labels:
    service: apifeed-pg
  name: apifeed-pg-svc
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: udacity-3-apifeed-pg
